version: "2.4"
services:
  nacos:
    image: leo18945/alpine-jre8-nacos:1.3.0
    init: true
    build:
      context: build
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./work/nacos/logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    image: nacos/nacos-mysql:5.7
    container_name: mysql
    env_file:
      - ./env/mysql.env
    volumes:
      - ./work/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - nacos
  #   restart: on-failure
  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:latest
  #   ports:
  #     - 3000:3000
  #   restart: on-failure

